server: 
  port: 9003
spring: 
  application:  
    name: huahua-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.117.83:3306/huahua_qa?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
###mybatis映射路径
mybatis:
  mapper-locations: classpath:mapping/*.xml


#日志级别
logging:
  level:
    root: info
